export const jobTitles = [
  "Part Time Treasure Hunter",
  "Train Pusher",
  "Ruby Guy",
  "Professional Mourner",
  "Discgraced Odor Judge",
  "Electrified Domino's Delivery Car",
  "Full Time Gimp",
  "Hungry Assistant Chef",
  "Rush Roadie",
  "Snake Milkman",
  "Old Youngman",
  "Part Time Jewel 'Borrower'",
  "Body Hair Enthusiast",
  "Tired CEO Sympathizer",
  "Horny Preacher",
  "Believable Alien",
  "Full Time Mom",
  "Cement Seer",
  "Oracle of the Ugly",
  "Seaman",
  "Freezing Cold Mayor",
  "YouTube Appraiser",
  "Gut Enthusiast",
  "Ice Cream Denier",
  "Warm Beef Appraiser",
  "Love Falcon",
  "DragonBall Z Historian",
  "Postpubescant",
  "Succession Critic",
  "Apartment Spear Hunter",
  "Thighdiver",
  "RateMyTeacher Admin",
  "Aquatic Hitman",
  "Disgraced Decathlete",
  "G.I. Joe Court Marshall",
  "Equine Attourney",
  "Mortuary Ventriloquist",
  "Space Apologist",
  "Weather Woman",
  "Dean of Emissions",
  "Honey Ham Corporate Advisor",
  "Harper's Bizarre Adventurer",
  "CBS Mornings Key Grip",
  "Semi-Pro Uncle",
  "Friday Night Morning Person",
  "6 Day Work Week Advocate",
  "Impersonal Bodyguard",
  "Library Hype Man",
  "Conservative Politician's Big Mistake",
  "Weekend Worrier",
  "Pantry Raider",
  "Retired Ohio Hater",
  "Homestar Runner Archivist",
  "AND1 Mixtape CC Transcriber",
  "The First Juggler",
  "Friendzone Entertainer",
  "Shiny Object Enthusiast",
  "30th Birthday Archivist",
  "Human Clown",
  "Scoliosis Ally",
  "Overpaid Teacher",
  "Overstimulated Company Man",
  "Jockey For The Tall Horses",
  "French",
  "Violent Poet",
  "Punches With Both Hands At Once",
];
