export const jobTitles = [
  "Part Time Treasure Hunter",
  "Train Pusher",
  "Ruby Guy",
  "Professional Mourner",
  "Discgraced Odor Judge",
  "Electrified Domino's Delivery Car",
  "Full Time Gimp",
  "Hungry Assistant Chef",
  "Rush Roadie",
  "Snake Milkman",
  "Old Youngman",
  "Part Time Jewel 'Borrower'",
  "Body Hair Enthusiast",
  "Tired CEO Sympathizer",
  "Horny Preacher",
  "Believable Alien",
  "Full Time Mom",
  "Cement Seer",
  "Oracle of the Ugly",
  "Seaman",
  "Freezing Cold Mayor",
  "YouTube Appraiser",
  "Gut Enthusiast",
  "Ice Cream Denier",
  "Warm Beef",
  "Love Falcon",
  "DragonBall Z Historian",
  "Postpubescant",
  "Succession Critic",
  "Apartment Spear Hunter",
  "Thighdiver",
  "RateMyTeacher Admin",
  "Aquatic Hitman",
  "Disgraced Olympic Long Jumper",
  "G.I. Joe Court Marshall",
  "Equine Attourney",
  "Mortuary Ventriloquist",
  "Space Apologist",
  "Weather Woman",
  "Dean of Emissions",
  "Honey Ham Corporate Advisor",
  "Harper's Bizarre Adventurer",
  "CBS Mornings Key Grip",
  "Semi-Pro Uncle",
  "Friday Night Morning Person",
  "6 Day Work Week Advocate",
  "Impersonal Bodyguard",
  "Public Bathroom Hype Boy",
  "Conservative Politician's Big Mistake",
  "Weekend Worrier",
  "Pantry Raider",
  "Retired Ohio Hater",
  "Homestar Runner Archivist",
  "AND1 Mixtape CC Transcriber",
  "The First Juggler",
  "Friendzone Entertainer",
  "Shiny Object Enthusiast",
  "31st Birthday Clown",
  "Human Accountant",
  "Scoliosis Ally",
  "Overpaid Teacher",
  "Overstimulated Company Man",
  "Jockey For The Tallest Horse",
  "French",
  "Violent Poet",
  "Traveling Vape Salesman",
  "Man Who Punches With Both Hands At Once",
  "Duke of Dallas",
  "Josh Duhamel",
  "Big Bible Boy",
  "#3 On Spirit Airlines' Please Fly List",
  "Host of Spike TV",
  "Precog",
  "Dry Heave Healer",
  "Nutter Butter Union Buster",
  "Exxon Cruise Director",
  "Local Crab",
  "Animatronic Medium",
  "H&M Hourly Associate",
  "Neighborhood Crystal Wizard",
  "Cameron Hunter",
  "Comment Section Advocate",
  "Shipyard Sinner",
  "Sony VAIO Warranty Author",
  "Guy Confused About ",
  "Four Piece Suit",
  "Rewatch Podcast Critic",
  "Spanx Spokesperson",
  "Private Prison Librarian",
  "Guy Who Tells Everyone He's Watched BET",
  "Monk With Debt",
  "Altitude Sick",
  "Erotic Stander",
  "Saxophone Repair Tech",
  "Used Gas Guzzler",
  "Rose-tinted Simpleton",
  "Degrassi Fandom Community Organizer",
  "One Tree Hill Tax Paying Resident",
  "Ruper Grint",
  "Tucson Comi-Con Degenerate",
  "2004 Nissan Xterra With The Premium Trim",
  "Bumble Deleter",
  "Little Stinker",
  "Ice Road Trucker, Warm Sprite Sucker",
  "Disney Adult Lawyer",
  "Book Club Promoter",
  "Pickelball Betting Ring Kingpin",
  "THE Final Fantasy",
  "Grass Seed Capital Of The World",
  "The Under Boss",
  "Middle Classist",
  "Creator of the Howie Mandela Effect",
  "Bubba Gump Assistant Manager",
  "Bidet Quality Control (Pants On)",
  "Pretty Bird",
  "Failed Experiment",
  "Sad Scientist",
  "Wide Load Stan",
  "Pompeii Truther",
  "Human Breathalizer (Breath In My Mouth)",
  "Robo-Orangutan",
  "Esports Pastor",
  "Digimon Harrassment Bureau",
  "Top 10 Viral Disease",
  "Fruit Stripe Gum Zebra",
  "Uncured Ham",
  "VR Sex Toy Positivity Guru",
  "XGames Nanny",
  "Halfpipe Heckler",
  "Kneefinder.com Moderator",
  "Pope Sean Paul III",
  "The Big Blue Rodeo Clown",
  "Zanerkand Abe Striker",
  "Shortwave Midwife",
  "Dopler Seuss",
  "Investment Juggalo",
  "Real Life Scorpion King",
  "Crank: High Voltage",
  "Most Neck Flaps",
  "Depressionist",
  "George W. Bush Art Collector",
  "Dense Dancer",
  "Corporate Shill",
  "Author Of: The Bible (Sweet James Version)",
  "Best Offers Only",
  "Box Office Don",
  "Green Honey From The Weed Bees",
  "Host Of 106.3 The Dumpy",
  "Nautical DJ",
  "Atlantis Insurance Adjuster",
  "Creatine Advocate",
  "Deep South Freeway Creature",
  "ROTC ASMR",
  "Updog Historian",
  "Large Marge Truther",
  "Arm & Hammer Stain Commander",
  "Guy Who Searched For Gru Nudes (Grudes)",
  "Hank Hill Erotica Author",
  "Lustful Wench",
  "Offroad Manga Blogger",
  "Chipped And Loving It",
  "Essential Oilspill",
  "Barmitzvah Jockey",
  "Ungovernable Ape",
  "Dreamcast Sock Puppet",
  "Chronically Underpaid",
  "Dobby Gravesite Tender",
  "Bitcoin Bitch",
  "Chicken Tender Influencer",
  "Dino Nuggie Sauce Boss",
  "High School Biology Teacher",
  "Paul Rudd's Teeth",
  "Stone Age Con Artist",
  "Consequence Ham",
  "Hospice Sniper",
  "Playstation 2 Corrupted Memory Card",
  "Craigslist DILF",
  "King Crimson",
  "Hungover Dog Lover",
  "LinkedIn Catfish Victim",
  "Your Milkman",
  "Two Journalists In A Trenchcoat",
  "Unfriendly Neighborhood Spy",
  "Local Coward",
  "Unsuccesful Clarevoyant",
  "Spectral Wedding Guest",
  "Ghost Officiant",
  "Distant Visible Imp",
  "Laser Lord",
  "Time Machine Sabetour",
  "Astral Projectionist",
  "Hotdog Fortune Teller",
  "Old Navy Lead Wrinkler",
  "Kohl's Cash Card Carrier",
  "Funk Athiest",
  "Got Surgery To Put More Ribs In",
  "Bankrupt Peperoni Man",
  "Classically Trained Grill Sergeant",
  "Cousin Judas"
];


